xterm -title "Server" -hold -e "./bin/Server server1 4242" 
xterm -title "Client 1" -hold -e "./bin/Client 1" 
xterm -title "Client 2" -hold -e "./bin/Client 2" 
xterm -title "Client 3" -hold -e "./bin/Client 3" 
xterm -title "Client 4" -hold -e "./bin/Client 4" 